# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: CI poc on actions

on:
  push:
    branches: 
      - master
      - release/*
  pull_request:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOCKER_USER: ${{ secrets.DOCKER_USER }}   
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: docker login
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: create docker image
      run: docker build -t helloworld-image .
    - name: Nexus Repo Publish
      uses: sonatype-nexus-community/nexus-repo-github-action@master
      with:
        serverUrl: http://localhost:8081/
        username: admin
        password: admin123
        format: maven2
        repository: docker-private
        coordinates: groupId=github-actions-poc artifactId=github-actions-poc version=latest
        filename: helloworld-image
